'diagnostic.error' = { underline = { color = "ruby4", style = "curl" } }
'diagnostic.hint' = { underline = { color = "emerald4", style = "curl" } }
'diagnostic.info' = { underline = { color = "sapphire4", style = "curl" } }
'diagnostic.warning' = { underline = { color = "topaz1", style = "curl" } }
'error' = { bg = "onyx3", fg = "ruby4", modifiers = ["bold"] }
'hint' = { fg = "emerald4", modifiers = ["bold"] }
'info' = { fg = "sapphire4", bg = "onyx3" }
'property' = { fg = "ruby1" }
'warning' = { fg ="topaz1", modifiers = ["bold"] }

'ui.background' = { bg = "onyx1"}
'ui.cursor' = { fg = "emerald1", bg = "diamond1" }
'ui.cursor.insert' = { fg = "emerald1", bg = "aquamarine1" }
'ui.cursor.match' = { fg = "emerald1", bg = "ruby1", modifiers = ["bold"] }
'ui.cursor.primary' = { fg = "emerald1", bg = "aquamarine1" }
'ui.cursor.select' = { fg = "emerald1", bg = "aquamarine1" }
'ui.cursorline.primary' = { bg = 'emerald4' }
'ui.gutter' = { }
'ui.help' = { bg = "onyx3", fg = "diamond1"}
'ui.highlight' = { bg = "emerald4"}
'ui.linenr' = { bg = "onyx3", fg = "diamond1"  }
'ui.linenr.selected' = { bg = "emerald1", fg = "diamond1", modifiers = [ "bold" ] }
'ui.menu' = { fg = "diamond1", bg = "onyx3" }
'ui.menu.selected' = { fg = "diamond1", bg = "topaz4" }
'ui.popup' = { bg = "onyx3" }
# 'ui.ppopup.info' = { bg = "emerald4", fg = "onyx3", modifiers = ["bold"] }
'ui.selection' = { bg = "sapphire1" }
'ui.selection.primary' = { bg = "sapphire1" }
'ui.statusline' = { fg = "diamond1", bg = "onyx3"}
'ui.statusline.inactive' = { fg = "diamond1", bg = "emerald1"}
'ui.statusline.insert' = { fg = "emerald1", bg = "amethyst4", modifiers = [ "bold" ] }
'ui.statusline.normal' = { fg = "emerald1", bg = "sapphire4", modifiers = [ "bold" ] }
'ui.statusline.select' = { fg = "emerald1", bg = "topaz1", modifiers = [ "bold" ] }
'ui.text' = { fg = "diamond1" }
'ui.text.focus' = { fg = "diamond1", bg = "onyx3", modifiers = ["bold"] }
'ui.text.info' = { }
'ui.virtual' = { fg = "emerald4" }
'ui.virtual.ruler' = { bg = "emerald4" }
'ui.virtual.whitespace' = { fg = "onyx3"}
'ui.virtual.indent-guide' = { fg = "onyx3" }
'ui.window' = { fg = "emerald4" }

'attribute' = { fg = "topaz1" }
'comment' = { fg = "emerald3" }
'comment.block' = { }
'comment.block.documentation' = { }
'comment.line' = { }
'constant' = { fg = "diamond1" }
'constant.builtin' = { fg = "topaz1", modifiers = ["bold"] }
'constant.builtin.boolean' = { }
'constant.character' = { fg = "topaz1"}
'constant.character.escape' = { fg = "topaz1", modifiers = ["bold"] }
'constant.numeric'  = { fg = "topaz1"}
# 'constant.numeric.integer' = { }
# 'constant.numeric.float' = { }
'diff.delta' = "ruby1"
# 'diff.delta.moved' = { }
'diff.minus' = "topaz1"
'diff.plus' = "emerald1"
'constructor' = { fg = "emerald4", modifiers = ["bold"]}
'function' = { fg = "topaz4"}
'function.builtin' = { fg = "topaz4" }
'function.method' = { fg = "topaz4" }
'function.macro' = { fg = "topaz4" }
'function.special' = { fg = "topaz4" }
'keyword' = { fg = "aquamarine1", modifiers = ["bold"] }
'keyword.control' = { fg = "aquamarine1", modifiers = ["bold"] }
'keyword.control.conditional' = { fg = "amethyst4", modifiers = ["bold"] }
'keyword.control.exception' = {fg = "aquamarine1", modifiers = ["bold"] }
'keyword.control.import' = { fg = "aquamarine1", modifiers = ["italic"] }
'keyword.control.repeat' = { fg = "amethyst4" }
'keyword.control.return' = { fg = "amethyst4" }
'keyword.directive' = { fg = "amethyst4" }
'keyword.function' = { fg = "aquamarine1" }
'keyword.operator' = { }
'label' = { fg = "amethyst1" }
'markup.bold' = { modifiers = ["bold"] }
'markup.heading' = { }
'markup.heading.1' = { }
'markup.heading.2' = { }
'markup.heading.3' = { }
'markup.heading.4' = { }
'markup.heading.5' = { }
'markup.heading.6' = { }
'markup.heading.completion' = { }
'markup.heading.marker' = { fg = "ruby1" }
'markup.heading.raw' = { }
'markup.italic' = { modifiers = ["italic"] }
'markup.link' = { fg = "sapphire4", modifiers = ["underlined"] }
'markup.link.label' = { }
'markup.link.text' = { fg = "amethyst1"}
'markup.link.url' = { }
'markup.list' = { fg = "ruby1" }
'markup.list.numbered' = { }
'markup.list.unnumbered' = { }
'markup.normal' = { }
'markup.normal.completion' = { }
'markup.normal.raw' = { }
'markup.quote' = { }
'markup.raw' = { }
'markup.raw.block' = { }
'markup.raw.inline' = { }
'markup.raw.inline.completion' = { }
'markup.raw.inline.hover' = { }
'markup.strikethrough' = { modifiers = ["crossed_out"] }
'namespace' = { fg = "emerald4" }
'operator' = { fg = "diamond1", modifiers = ["bold"] }
'punctuation' =  { fg = "diamond1", modifiers = ["bold"] }
'punctuation.delimiter' = { fg = "diamond1" }
'punctuation.bracket' = { fg = "topaz1" }
'special' = { fg = "diamond1"}
'string' = { fg = "topaz1" }
'string.regexp' = { }
'string.special' = { fg = "sapphire4" }
'string.special.path' = { }
'string.special.symbol' = { }
'string.special.url' = { }
'tag' = { fg = "topaz1"}
'type' = { fg = "emerald4"}
#'type.builtin' = { }
#'type.enum.variant' = { }
'variable' = { fg = "aquamarine3" }
'variable.builtin' = { fg = "aquamarine3" }
'variable.function' = { fg = "aquamarine3" }
'variable.other.member' = { fg = "aquamarine3" }
'variable.parameter' = { fg = "aquamarine3" }

[palette]
onyx1 = "#040404"
onyx2 = "#100f0f"
onyx3 = "#1e1e1d"
onyx4 = "#2d2c2c"

ruby1 = "#af1506"
ruby2 = "#c02310"
ruby3 = "#cd321c"
ruby4 = "#dc4025"

emerald1 = "#257d10"
emerald2 = "#2e871a"
emerald3 = "#45a52d"
emerald4 = "#55a93f"

sapphire1 = "#00327b"
sapphire2 = "#003b83"
sapphire3 = "#0e4a8a"
sapphire4 = "#275a8c"

aquamarine1 = "#3b96bf"
aquamarine2 = "#5badce"
aquamarine3 = "#83c0d2"
aquamarine4 = "#aacbd2"

amethyst1 = "#5b144b"
amethyst2 = "#64245b"
amethyst3 = "#703b6c"
amethyst4 = "#7a4e74"

topaz1 = "#bc7800"
topaz2 = "#b78005"
topaz3 = "#ca900e"
topaz4 = "#c6981b"

diamond1 = "#d0d9d7"
diamond2 = "#d4d9cc"
diamond3 = "#e0d3cb"
diamond4 = "#e4dcc0"
